### ISSUE TITLE
ValueError issue

### ISSUE THREAD

**Issue by XDxc-cuber** [amarlearning/Finger-Detection-and-Tracking#22]
I got this after pressing 'z' and I have no idea about this. T T

[ WARN:0@0.154] global C:\b\abs_5e60wdx8td\croots\recipe\opencv-suite_1663884119901\work\modules\videoio\src\cap_gstreamer.cpp (862) cv::GStreamerCapture::isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
QMimeDatabase: Error loading internal MIME data
An error has been encountered at line 1 of <internal MIME data>: Premature end of document.:
Traceback (most recent call last):
  File "c:\Users\20227\Desktop\git_pull\Finger-Detection-and-Tracking\Finger Detection and Tracking\FingerDetection.py", line 175, in <module>
    main()
  File "c:\Users\20227\Desktop\git_pull\Finger-Detection-and-Tracking\Finger Detection and Tracking\FingerDetection.py", line 160, in main
    manage_image_opr(frame, hand_hist)
  File "c:\Users\20227\Desktop\git_pull\Finger-Detection-and-Tracking\Finger Detection and Tracking\FingerDetection.py", line 124, in manage_image_opr
    contour_list = contours(hist_mask_image)
  File "c:\Users\20227\Desktop\git_pull\Finger-Detection-and-Tracking\Finger Detection and Tracking\FingerDetection.py", line 23, in contours
    _, cont, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by KoneMango** [comment]
@XDxc-cuber This may be because you are using a new version of opencv, the new version of opencv no longer requires the _ placeholder for findContours, so just remove the "_," from this line of code and it will work fine. Wish this will help you.

**Comment by amarlearning** [comment]
issue has been fixed now
