### ISSUE TITLE
Program terminates after entering z

### ISSUE THREAD

**Issue by freycesar** [amarlearning/Finger-Detection-and-Tracking#23]
Error: Traceback (most recent call last):
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 175, in <module>
    main()
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 160, in main
    manage_image_opr(frame, hand_hist)
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 124, in manage_image_opr
    contour_list = contours(hist_mask_image)
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 23, in contours
    _, cont, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
PS C:\Users\29442> & C:/Users/29442/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/29442/Desktop/AUTD/REALsense/Finger-Detection-and-Tracking-master/Finger-Detection-and-Tracking-master/Finger Detection and Tracking/FingerDetection.py"
Traceback (most recent call last):
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 175, in <module>
    main()
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 160, in main
    manage_image_opr(frame, hand_hist)
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 124, in manage_image_opr
    contour_list = contours(hist_mask_image)
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 23, in contours
    _, cont, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
PS C:\Users\29442> & C:/Users/29442/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/29442/Desktop/AUTD/REALsense/Finger-Detection-and-Tracking-master/Finger-Detection-and-Tracking-master/Finger Detection and Tracking/FingerDetection.py"
Traceback (most recent call last):
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 175, in <module>
    main()
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 160, in main
    manage_image_opr(frame, hand_hist)
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 124, in manage_image_opr
    contour_list = contours(hist_mask_image)
  File "c:\Users\29442\Desktop\AUTD\REALsense\Finger-Detection-and-Tracking-master\Finger-Detection-and-Tracking-master\Finger Detection and Tracking\FingerDetection.py", line 23, in contours
    _, cont, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by amarlearning** [comment]
issue has been fixed now
